// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('moment.moment-filter', []).filter('moment', [
    'moment', function(moment) {
      return function(input, format, formatFrom) {
        if (format == null) {
          format = "L";
        }
        if (formatFrom == null) {
          formatFrom = false;
        }
        if (!formatFrom) {
          return moment(input, "YYYY-MM-DD HH:mm").format(format);
        } else {
          return moment(input, formatFrom).format(format);
        }
      };
    }
  ]);

}).call(this);
