// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('moment.moment-filter', []).filter('moment', [
    'moment', function(moment) {
      return function(input, format) {
        if (format == null) {
          format = "L";
        }
        return moment(input).format(format);
      };
    }
  ]);

}).call(this);
