// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var FillText;

  angular.module('filltext.filltext-service', []).service('filltext', [
    '$http', FillText = (function() {
      function FillText($http) {
        this.$http = $http;
      }

      FillText.prototype.getRecords = function(rows) {
        if (rows == null) {
          rows = 10;
        }
        return this.$http.jsonp('http://filltext.com', {
          params: {
            rows: rows,
            name: '{firstName}',
            surname: '{lastName}',
            callback: 'JSON_CALLBACK'
          }
        });
      };

      FillText.prototype.getRecordsBackUp = function() {
        return this.$http.get('/filltext.json');
      };

      return FillText;

    })()
  ]);

}).call(this);
